name: Build FCL for Windows (CLANG) via Conda
on: [push,pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [windows-latest-clang-cl]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

        include:
          - name: windows-latest-clang-cl
            os: windows-2019
            compiler: clang-cl

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Cache conda
      uses: actions/cache@v2
      env:
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ matrix.python-version }}-${{ env.CACHE_NUMBER }}-${{
          hashFiles('.github/workflows/conda/conda-env.yml') }}
    - uses: conda-incubator/setup-miniconda@v2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        activate-environment: fcl
        environment-file: .github/workflows/conda/conda-env.yml
        python-version: ${{ matrix.python-version }}
        use-only-tar-bz2: true
    - name: Install cmake and update conda
      run: |
        conda install cmake -c main
    - name: Build FCL
      shell: cmd /C CALL {0}
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |
        %CONDA_PREFIX%\python -V
        :: unset extra Boost envs
        set Boost_ROOT=
        set BOOST_ROOT_1_69_0=
        set BOOST_ROOT_1_72_0=
        set PATH=%PATH:C:\hostedtoolcache\windows\Boost\1.72.0;=%

        call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64

        :: Create build
        mkdir build
        pushd build

        :: Configure
        set PKG_CONFIG_PATH=%CONDA_PREFIX%\Library\share\pkgconfig:%CONDA_PREFIX%\Library\share\pkgconfig
        mkdir out
        cmake ^
          -G "Visual Studio 16 2019" -T "ClangCl" -DCMAKE_GENERATOR_PLATFORM=x64 ^
          -DCMAKE_INSTALL_PREFIX=%CONDA_PREFIX%\Library ^
          -DCMAKE_BUILD_TYPE=Release ^
          -DGENERATE_PYTHON_STUBS=OFF ^
          -DPYTHON_SITELIB="%CD%\out" ^
          -DPYTHON_EXECUTABLE=%CONDA_PREFIX%\python.exe ^
          -DHPP_FCL_HAS_QHULL=ON ^
          -DBUILD_PYTHON_INTERFACE=ON ^
          ..
        if errorlevel 1 exit 1

        :: Build and Install
        cmake --build . --config Release --target install
<<<<<<< HEAD
        cp src\Release\hpp-fcl.dll out\hppfcl
        cp %CONDA_PREFIX%\Library\bin\assimp-vc141-mt.dll out\hppfcl
        cp %CONDA_PREFIX%\Library\bin\boost_serialization.dll out\hppfcl
        cp %CONDA_PREFIX%\Library\bin\eigenpy.dll out\hppfcl
        cp %CONDA_PREFIX%\Library\bin\qhull_r.dll out\hppfcl
        cp %CONDA_PREFIX%\Library\bin\zlib.dll out\hppfcl
        python -c "import shutil, os; shutil.copy(os.environ['CONDA_PREFIX'] + '\\Library\\bin\\boost_python' + '${{ matrix.python-version }}'.replace('.', '') + '.dll', 'out\\hppfcl')"
        if errorlevel 1 exit 1

        :: Build stubs
        set PYTHONPATH=out
        git clone https://github.com/jcarpent/pybind11-stubgen.git
        python "%CD%\pybind11-stubgen\pybind11_stubgen\__init__.py" -o %CONDA_PREFIX%\Lib\site-packages hppfcl --boost-python --ignore-invalid signature --no-setup-py --root-module-suffix ""

        cp -r out\hppfcl %CONDA_PREFIX%\Lib\site-packages

        :: Testing
        ctest --output-on-failure -C Release -V
        if errorlevel 1 exit 1

        :: Test Python import
        cd ..
        python -c "import hppfcl"
        if errorlevel 1 exit 1
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: python${{ matrix.python-version }}
        path: build/out/*
